// Local file loading, worker lifecycle, revision handling, and verified download bytes.
// Engine readiness is deliberately separate from preview-processing status.
import { fileMatchesFormats, formatLabel, formatListLabel } from "../formats.js";
import { inputProblem } from "../input.js";
import { downloadedFileName } from "../names.js";
import { createProcessingClient, getProcessingScheduler } from "../processing/client.js";

export function attachEditorProcessing(editor) {
  const { elements, state } = editor;

  function isSupportedInput(file) {
    return fileMatchesFormats(file, state.capabilities.inputFormats);
  }

  function unsupportedInputMessage() {
    return `That image format is not supported yet. Try ${formatListLabel(state.capabilities.inputFormats)}.`;
  }

  function setEngineFailure(message) {
    rejectPreviewRequest(new Error(message));
    state.enginePhase = "error";
    clearTimeout(state.readyTimer);
    editor.setEngineStatus("Not ready", "error");
    editor.setProcessingStatus(message, false, true);
  }

  function revokeResult() {
    if (state.result?.url) URL.revokeObjectURL(state.result.url);
    state.result = null;
  }

  function invalidateResult() {
    state.worker?.cancelPending();
    state.revision += 1;
    revokeResult();
    editor.renderOutputSummary();
  }

  function revokeSource() {
    if (state.sourceUrl) URL.revokeObjectURL(state.sourceUrl);
    state.sourceUrl = null;
  }

  function scheduleProcessing() {
    clearTimeout(state.scheduleTimer);
    if (!state.file || !state.operations) return;
    editor.syncProjectPreview();
    state.processingError = null;
    invalidateResult();
    window.dispatchEvent(new CustomEvent("tinystar:editor-changed"));
    if (state.enginePhase !== "ready") {
      editor.setProcessingStatus("The editor is getting ready…", true);
      return;
    }
    editor.setProcessingStatus("Updating preview…", true);
    state.scheduleTimer = setTimeout(processCurrent, 90);
  }

  function processCurrent() {
    if (!state.file || !state.operations || state.enginePhase !== "ready") return;
    const source = state.file;
    const file = { id: source.id, name: source.name };
    const settings = editor.projectOperations();
    // Batch recipes carry maxWidth/maxHeight for their fit pipeline. Once the
    // image is on the canvas, exact resize controls are authoritative and the
    // derived bounds must follow them or a 4 × 4 edit can export at the old
    // recipe size.
    settings.maxWidth = settings.resizeWidth;
    settings.maxHeight = settings.resizeHeight;
    const message = { type: "process", jobId: "editor", revision: state.revision, files: [file], settings };
    getProcessingScheduler().setRetainedBytes("editor", source.bytes.byteLength + state.image.naturalWidth * state.image.naturalHeight * 4);
    state.worker.submit({ message,
      source: { width: state.image.naturalWidth, height: state.image.naturalHeight, encodedBytes: source.bytes.byteLength },
      prepare: () => {
        const bytes = source.bytes.buffer.slice(source.bytes.byteOffset, source.bytes.byteOffset + source.bytes.byteLength);
        return { message: { ...message, files: [{ ...file, bytes }] }, transfer: [bytes] };
      },
    });
  }

  function downloadResult() {
    const result = state.result;
    if (!result || result.revision !== state.revision) return;
    const url = URL.createObjectURL(new Blob([result.output], { type: result.mime }));
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = downloadedFileName(
      state.file?.name,
      state.operations?.presetName ?? state.operations?.presetId ?? "edited",
      result.format ?? state.operations?.format,
    );
    anchor.click();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
    state.savedOperations = editor.cloneOperations();
    editor.updateDirtyState();
    editor.setProcessingStatus(`Download started for the current ${formatLabel(result.format ?? state.operations?.format)} image.`);
    if (elements.exportDialog.open) elements.exportDialog.close();
  }

  function openExportDialog() {
    const result = state.result && state.result.revision === state.revision ? state.result : null;
    if (!result) {
      editor.setProcessingStatus("The preview is not ready yet.");
      return;
    }
    elements.exportDialogStatus.textContent = "Your image stays on this device.";
    if (typeof elements.exportDialog.showModal === "function") elements.exportDialog.showModal();
    else elements.exportDialog.setAttribute("open", "");
  }

  function saveOrOpenExport() {
    const result = state.result && state.result.revision === state.revision ? state.result : null;
    if (!result) {
      editor.setProcessingStatus("The preview is not ready yet.");
      return;
    }
    // With one verified output format and no quality choice, Download has no
    // meaningful decision to ask the user to make. Download the authoritative
    // generated bytes immediately. Keep the metadata-only sheet when an
    // engine exposes multiple formats or a lossy choice.
    const unambiguous = state.capabilities.outputFormats.length === 1
      && !state.capabilities.compression.lossy
      && state.capabilities.outputFormats[0] === result.format;
    if (unambiguous) downloadResult();
    else openExportDialog();
  }

  function loadImage(url) {
    return new Promise((resolve, reject) => {
      const image = new window.Image();
      image.onload = () => resolve(image);
      image.onerror = () => reject(new Error("preview unavailable"));
      image.src = url;
    });
  }

  function rejectPreviewRequest(error) {
    const pending = state.previewRequest;
    if (!pending) return;
    state.previewRequest = null;
    pending.reject(error);
  }

  function postPreviewRequest() {
    const pending = state.previewRequest;
    if (!pending || pending.sent || !state.worker || state.enginePhase !== "ready" || !state.file?.bytes) return;
    const source = state.file;
    pending.sent = true;
    const message = {
      type: "preview",
      revision: pending.revision,
      file: { id: source.id, name: source.name },
    };
    state.worker.submit({ message, source: { encodedBytes: source.bytes.byteLength }, prepare: () => {
      const bytes = source.bytes.buffer.slice(source.bytes.byteOffset, source.bytes.byteOffset + source.bytes.byteLength);
      return { message: { ...message, file: { ...message.file, bytes } }, transfer: [bytes] };
    } });
  }

  function requestPreviewProxy(file, token) {
    return new Promise((resolve, reject) => {
      state.previewRequest = { token, revision: state.revision, resolve, reject, sent: false };
      postPreviewRequest();
    });
  }

  function inputError(problem) {
    const error = new Error(problem.message);
    error.userMessage = problem.message;
    error.code = problem.code;
    return error;
  }

  function commitImportedImage(file, bytes, image, sourceUrl, token, incomingOperations, incomingContext, incomingProject) {
    if (token !== state.loadToken) {
      URL.revokeObjectURL(sourceUrl);
      return false;
    }
    state.sourceUrl = sourceUrl;
    state.file.bytes = bytes;
    state.image = image;
    state.activeTextId = null;
    const defaults = editor.defaultOperations();
    state.operations = incomingOperations ? { ...defaults, ...editor.cloneOperations(incomingOperations), crop: editor.cloneRect(incomingOperations.crop) } : defaults;
    editor.resetProject(incomingProject);
    editor.syncActiveText?.();
    state.savedOperations = editor.cloneOperations();
    editor.setProcessingStatus(state.enginePhase === "ready" ? "Image ready. Adjust it on the canvas." : "Image ready. The editor is still starting…", state.enginePhase !== "ready");
    editor.renderAll();
    window.dispatchEvent(new CustomEvent("tinystar:editor-loaded", { detail: { file, context: incomingContext } }));
    if (state.enginePhase === "ready") scheduleProcessing();
    return true;
  }

  async function importImage(file, incomingOperations = null, incomingContext = null, incomingProject = null) {
    if (!file || file.size === 0) return;
    if (!isSupportedInput(file)) {
      editor.setProcessingStatus(unsupportedInputMessage(), false, true);
      return;
    }
    const token = ++state.loadToken;
    state.worker?.cancelPending();
    rejectPreviewRequest(new Error("A newer image was opened."));
    state.revision += 1;
    revokeResult();
    revokeSource();
    state.editorContext = incomingContext;
    state.file = {
      id: `${file.name}-${file.lastModified}-${token}`,
      name: file.name,
      type: file.type || "application/octet-stream",
      lastModified: file.lastModified || 0,
      size: file.size || 0,
      bytes: null,
    };
    state.image = null;
    state.operations = null;
    state.projectHistory = null;
    state.savedOperations = null;
    state.processingError = null;
    state.history = [];
    state.future = [];
    state.tool = "move";
    state.zoom = 1;
    state.panX = 0;
    state.panY = 0;
    elements.fileName.textContent = file.name;
    editor.setProcessingStatus("Reading the image on this device…", true);
    editor.renderAll();
    try {
      const bytes = new Uint8Array(await file.arrayBuffer());
      const byteProblem = inputProblem(bytes);
      if (byteProblem) throw inputError(byteProblem);
      state.file.bytes = bytes;
      const sourceUrl = URL.createObjectURL(file);
      try {
        const image = await loadImage(sourceUrl);
        const dimensionProblem = inputProblem(bytes, { width: image.naturalWidth, height: image.naturalHeight });
        if (dimensionProblem) throw inputError(dimensionProblem);
        commitImportedImage(file, bytes, image, sourceUrl, token, incomingOperations, incomingContext, incomingProject);
      } catch (error) {
        if (error?.userMessage) throw error;
        URL.revokeObjectURL(sourceUrl);
        if (token !== state.loadToken) return;
        const proxy = await requestPreviewProxy(file, token);
        if (token !== state.loadToken) {
          URL.revokeObjectURL(proxy.url);
          return;
        }
        const proxyProblem = inputProblem(bytes, { width: proxy.width, height: proxy.height });
        if (proxyProblem) {
          URL.revokeObjectURL(proxy.url);
          throw inputError(proxyProblem);
        }
        commitImportedImage(file, bytes, proxy.image, proxy.url, token, incomingOperations, incomingContext, incomingProject);
      }
    } catch (error) {
      if (token !== state.loadToken) return;
      state.file = null;
      state.image = null;
      state.operations = null;
      editor.setProcessingStatus(error?.userMessage ?? "This image could not be previewed in this browser.", false, true);
      editor.renderAll();
    }
  }

  function clearImage() {
    state.worker?.cancelPending();
    getProcessingScheduler().setRetainedBytes("editor", 0);
    state.loadToken += 1;
    state.revision += 1;
    clearTimeout(state.scheduleTimer);
    rejectPreviewRequest(new Error("The image was cleared."));
    revokeResult();
    revokeSource();
    state.file = null;
    state.image = null;
    state.operations = null;
    state.projectHistory = null;
    state.savedOperations = null;
    state.processingError = null;
    state.history = [];
    state.future = [];
    state.editorContext = null;
    state.activeTextId = null;
    state.tool = "move";
    state.inspectorOpen = false;
    state.preview = "edited";
    state.cropDraft = null;
    state.cropAspect = null;
    state.zoom = 1;
    state.panX = 0;
    state.panY = 0;
    state.drag = null;
    editor.setProcessingStatus("Open an image to begin.");
    editor.renderAll();
  }

  function startWorker() {
    if (state.worker) state.worker.terminate();
    state.enginePhase = "starting";
    editor.setEngineStatus("Starting…", "starting");
    state.worker = createProcessingClient({ priority: 0, latestOnly: true });
    state.worker.addEventListener("message", (event) => {
      const message = event.data;
      if (message.type === "init-start") {
        state.enginePhase = "starting";
        editor.setEngineStatus("Starting…", "starting");
        return;
      }
      if (message.type === "ready") {
        state.enginePhase = "ready";
        clearTimeout(state.readyTimer);
        editor.setCapabilities(message);
        editor.setEngineStatus("Ready", "ready");
        editor.setProcessingStatus(state.image ? "Image ready. Adjust it on the canvas." : "Open an image to begin.");
        if (state.previewRequest) postPreviewRequest();
        else if (state.file && state.image) scheduleProcessing();
        return;
      }
      if (message.type === "preview-result" && message.revision === state.revision) {
        const pending = state.previewRequest;
        if (!pending || pending.revision !== message.revision) return;
        state.previewRequest = null;
        const bytes = new Uint8Array(message.output);
        const url = URL.createObjectURL(new Blob([bytes], { type: message.mime }));
        loadImage(url).then((image) => {
          if (pending.token !== state.loadToken) {
            URL.revokeObjectURL(url);
            return;
          }
          pending.resolve({ url, image, width: message.width, height: message.height });
        }).catch((error) => {
          URL.revokeObjectURL(url);
          pending.reject(error);
        });
        return;
      }
      if (message.type === "preview-error" && message.revision === state.revision) {
        const pending = state.previewRequest;
        state.previewRequest = null;
        pending?.reject(new Error(message.message || "The image preview could not be created."));
        return;
      }
      if (message.type === "result" && message.revision === state.revision) {
        const bytes = new Uint8Array(message.output);
        acceptResult({ ...message, output: bytes });
        return;
      }
      if (message.type === "file-error" && message.revision === state.revision) {
        revokeResult();
        state.processingError = message.message;
        editor.setProcessingStatus(message.message, false, true);
        editor.renderOutputSummary();
        return;
      }
      if (message.type === "done" && message.revision === state.revision) {
        editor.setProcessingStatus(
          state.result ? "Ready to download." : state.processingError ?? "The preview could not be created.",
          false,
          !state.result,
        );
        editor.renderOutputSummary();
        return;
      }
      if (message.type === "fatal-error") setEngineFailure("The editor could not start. Refresh the page and try again.");
    });
    state.worker.addEventListener("error", () => setEngineFailure("The editor stopped unexpectedly. Refresh the page and try again."));
    clearTimeout(state.readyTimer);
    state.readyTimer = setTimeout(() => {
      if (state.enginePhase === "starting") {
        editor.setEngineStatus("Still starting…", "starting");
        editor.setProcessingStatus("The editor is taking a little longer to start. Keep this tab open or refresh to retry.", true);
      }
    }, 8000);
  }

  function acceptResult(message) {
    if (state.revision !== message.revision) return;
    revokeResult();
    getProcessingScheduler().setRetainedBytes("editor", (state.file?.bytes?.byteLength ?? 0)
      + (state.image?.naturalWidth ?? 0) * (state.image?.naturalHeight ?? 0) * 4 + message.output.byteLength * 2);
    const outputUrl = URL.createObjectURL(new Blob([message.output], { type: message.mime }));
    state.result = {
      ...message,
      output: message.output instanceof Uint8Array ? message.output : new Uint8Array(message.output),
      outputBytes: message.outputBytes ?? message.output.byteLength,
      url: outputUrl,
    };
    state.processingError = null;
    editor.setProcessingStatus("Preview ready.");
    editor.renderOutputSummary();
    editor.loadImage(outputUrl).then((image) => {
      if (state.result?.revision !== message.revision || state.result?.url !== outputUrl) return;
      state.result.image = image;
      editor.renderCanvas();
    }).catch(() => {
      // The generated bytes remain the authoritative download result even if
      // the browser cannot decode the preview URL.
    });
  }

  Object.assign(editor, {
    isSupportedInput,
    supportedInputLabel: () => formatListLabel(state.capabilities.inputFormats),
    revokeResult,
    invalidateResult,
    revokeSource,
    scheduleProcessing,
    processCurrent,
    downloadResult,
    openExportDialog,
    saveOrOpenExport,
    loadImage,
    importImage,
    clearImage,
    startWorker,
  });
}
